'use strict';

const ROUTES = [
  ['home','Home'],['tournaments','Tournament Center'],['scoreboard','Full Scoreboard'],['ranking','Ranking'],
  ['scorecard','Player Scorecards'],['halloffame','Hall of Fame'],['statistics','Statistics'],['import','Data Import'],
  ['about','About FLPR'],['appendix','Appendix & Definitions']
];

const TOURNAMENTS = [
  {id:'T5',name:'JakSel T5 – Weekly Americano',date:'20 July 2026',location:'Jakarta Selatan',format:'Americano',courts:2,players:9,totalPoints:140,podium:[['Austin',23],['Sandy',22],['Michael',19]],status:'Complete'},
  {id:'T4',name:'JakSel T4 – Weekly Americano',date:'06 July 2026',location:'Jakarta Selatan',format:'Americano',status:'Awaiting verified historical import'},
  {id:'T3',name:'JakSel T3 – Weekly Americano',date:'29 June 2026',location:'Jakarta Selatan',format:'Americano',status:'Awaiting verified historical import'},
  {id:'T2',name:'JakSel T2 – Weekly Americano',date:'22 June 2026',location:'Jakarta Selatan',format:'Americano',status:'Awaiting verified historical import'},
  {id:'T1',name:'JakSel T1 – Weekly Americano',date:'15 June 2026',location:'Jakarta Selatan',format:'Americano',status:'Awaiting verified historical import'}
];

const ARCHIVE_KEY='flpr_verified_tournaments_v1';
function loadImportedTournaments(){try{const raw=localStorage.getItem(ARCHIVE_KEY);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[];}catch(e){console.warn('Archive load failed',e);return [];}}
function getTournaments(){const imported=loadImportedTournaments();const ids=new Set(imported.map(t=>t.id));return [...imported,...TOURNAMENTS.filter(t=>!ids.has(t.id))].sort((a,b)=>String(b.dateISO||b.date).localeCompare(String(a.dateISO||a.date)));}
function saveImportedTournament(t){const current=loadImportedTournaments().filter(x=>x.id!==t.id);current.push(t);localStorage.setItem(ARCHIVE_KEY,JSON.stringify(current));}

const PHOTO = {
  'austin':'player-austin.jpg','michael':'player-michael.jpg','edy-sp':'player-edy-sp.jpg',
  'alwin':'player-alwin.jpg','donny':'player-donny.jpg','ronald':'player-ronald.jpg','thohir':'player-thohir.jpg','welly':'player-welly.jpg',
  'nicholas':'player-nicholas.jpg','david':'player-david.jpg','hansen':'player-hansen.jpg','ricky':'player-ricky.jpg','reza':'player-reza.jpg','kennard':'player-kennard.jpg',
  'sandy':'player-sandy.jpg'
};

let DATA = null;
const app = document.getElementById('app');
const drawer = document.getElementById('drawer');
const menuButton = document.getElementById('menuButton');
const backdrop = document.getElementById('backdrop');

function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function slugify(v=''){return String(v).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function avatar(name){return PHOTO[slugify(name)] || 'generic-padel-avatar.svg';}
function route(){const raw=location.hash.replace(/^#/,'')||'home';const [name,param]=raw.split('/');return {name:ROUTES.some(r=>r[0]===name)?name:'home',param:decodeURIComponent(param||'')};}
function navLink(id,label){return `<a href="#${id}" data-route="${id}">${label}</a>`;}
function buildDrawer(){drawer.innerHTML=`<div class="drawer-head"><strong>FLPR Menu</strong><button class="drawer-close" id="drawerClose" aria-label="Close menu">×</button></div>${ROUTES.map(r=>navLink(...r)).join('')}`;}
function setMenu(open){drawer.classList.toggle('open',open);drawer.setAttribute('aria-hidden',String(!open));menuButton.setAttribute('aria-expanded',String(open));backdrop.hidden=!open;document.body.style.overflow=open?'hidden':'';}
function title(t,s){return `<h1 class="page-title">${escapeHtml(t)}</h1><p class="subtitle">${escapeHtml(s)}</p>`;}
function stats(items){return `<div class="grid stats">${items.map(([a,b])=>`<div class="stat"><span>${escapeHtml(a)}</span><strong>${escapeHtml(b)}</strong></div>`).join('')}</div>`;}
function pct(v){return `${Number(v||0).toFixed(1)}%`;}
function signed(v){const n=Number(v||0);return `${n>0?'+':''}${n.toFixed(2)}`;}
function badge(text,cls=''){return `<span class="badge ${cls}">${escapeHtml(text)}</span>`;}

const STAT_INFO = {
  'average-rating': {title:'Average Rating',definition:'The arithmetic mean of all current FLPR ratings.',formula:'Sum of current player ratings ÷ number of ranked players.',interpretation:'Use this to track the overall level of the active pool over time. It is not a target score for an individual player.'},
  'rating-spread': {title:'Rating Spread',definition:'The distance between the highest and lowest current FLPR rating.',formula:'Highest rating − lowest rating.',interpretation:'A smaller spread generally indicates a tighter field; a larger spread indicates wider skill separation.'},
  'balance-index': {title:'Competitive Balance Index',definition:'A workbook-derived indicator of how evenly matched the active competition is.',formula:'Normalized inverse dispersion of player performance, expressed on a 0–100 scale.',interpretation:'Higher values indicate a more balanced field. Read it together with rating spread and sample size.'},
  'average-win-rate': {title:'Average Win Rate',definition:'The average recorded win rate across all players.',formula:'Sum of individual win rates ÷ number of players.',interpretation:'Useful as a dataset integrity check. In a closed and balanced pool it usually stays close to 50%.'},
  'top-movers': {title:'Top Movers',definition:'Players with the largest official upward rank movement between approved FLPR snapshots.',formula:'Previous official rank − current official rank.',interpretation:'Positive values mean the player moved upward. The baseline release shows neutral movement until a later verified snapshot exists.'},
  'momentum-leaders': {title:'Momentum Leaders',definition:'Players with the strongest current form profile.',formula:'55% Recent Form + 25% Clutch + 20% Adjusted Win Rate.',interpretation:'Momentum is responsive to current form and can change faster than rating. It is not a replacement for long-term ranking.'},
  'most-consistent': {title:'Most Consistent',definition:'Players whose recorded performance varies least from match to match.',formula:'Workbook consistency index normalized to 0–100.',interpretation:'High consistency means reliability, not necessarily the highest peak performance.'},
  'highest-win-rate': {title:'Highest Win Rate',definition:'Players with the highest percentage of recorded match wins.',formula:'Wins ÷ matches × 100.',interpretation:'A minimum-match threshold is applied to reduce small-sample distortion.'},
  'most-dominant': {title:'Most Dominant',definition:'Players who create the strongest point-margin control in their recorded matches.',formula:'Workbook dominance index based on point differential and result strength.',interpretation:'Dominance distinguishes narrow wins from convincing performances.'},
  'clutch-leaders': {title:'Clutch Leaders',definition:'Players who perform best in close and high-pressure matches.',formula:'Workbook clutch index based on outcomes in narrow-margin matches.',interpretation:'A high score suggests composure under pressure; it should be read with sample size.'},
  'most-versatile': {title:'Most Versatile',definition:'Players who remain effective across different partner combinations.',formula:'Workbook versatility index normalized to 0–100.',interpretation:'Higher values suggest adaptability rather than dependence on one preferred partner.'},
  'toughest-schedule': {title:'Toughest Schedule',definition:'Players who have faced the strongest overall opposition.',formula:'Average opponent strength adjusted for match volume.',interpretation:'This gives context when raw win rate understates performance against strong opponents.'},
  'best-partner-chemistry': {title:'Best Partner Chemistry',definition:'The strongest recorded partnership effect for each player.',formula:'Performance with the partner minus the player’s normal baseline.',interpretation:'A positive chemistry delta suggests the partnership performs above expectation.'},
  'toughest-opponent': {title:'Toughest Opponent',definition:'The opponent who has created the greatest recorded challenge for each player.',formula:'Head-to-head win rate, sample size, and point differential combined.',interpretation:'Use this as a matchup insight, not as a claim of absolute superiority.'},
  'rank': {title:'Rank',definition:'The player’s current official position in the FLPR standings.',formula:'Players are ordered by the approved FLPR ranking engine and tie-break rules.',interpretation:'A lower number is better. Rank reflects relative standing, while rating shows the underlying performance score.'},
  'player': {title:'Player',definition:'The registered FLPR player identity linked to the player scorecard.',formula:'Matched from the master player database using the approved player name and unique slug.',interpretation:'Click a player name to open the complete individual scorecard.'},
  'matches': {title:'Matches',definition:'The number of valid recorded matches included in the current FLPR dataset.',formula:'Count of approved match records involving the player.',interpretation:'A larger sample generally makes rating and statistics more reliable.'},
  'wins': {title:'Wins',definition:'The number of valid recorded matches won by the player.',formula:'Count of approved matches where the player’s team finished with the higher score.',interpretation:'Read together with matches, win rate, opponent strength, and point dominance.'},
  'losses': {title:'Losses',definition:'The number of valid recorded matches lost by the player.',formula:'Count of approved matches where the player’s team finished with the lower score.',interpretation:'Losses are contextualized by schedule strength, partner combinations, and score margin.'},
  'win-rate': {title:'Win Rate',definition:'The percentage of valid recorded matches won by the player.',formula:'Wins ÷ matches × 100.',interpretation:'Higher is better, but small samples and opponent strength can affect interpretation.'},
  'rating': {title:'FLPR Rating',definition:'The player’s current underlying performance rating in the FLPR system.',formula:'Workbook-derived rating using approved results, performance strength, and reliability adjustments.',interpretation:'Higher values indicate stronger demonstrated performance. Rating and rank are related but not identical.'},
  'consistency': {title:'Consistency',definition:'An index of how stable the player’s performance is from match to match.',formula:'Workbook consistency model normalized to a 0–100 scale.',interpretation:'Higher values indicate dependable performance with less variation.'},
  'momentum': {title:'Momentum',definition:'A current-form indicator designed to react faster than the long-term rating.',formula:'55% Recent Form + 25% Clutch + 20% Adjusted Win Rate.',interpretation:'Higher values indicate stronger recent form. Momentum can change quickly after new tournaments.'},
  'handicap': {title:'Handicap',definition:'The FLPR balancing adjustment assigned to help create more competitive formats.',formula:'Workbook-derived from demonstrated ability, rating, reliability, and the approved handicap policy.',interpretation:'A positive or stronger handicap reflects higher demonstrated ability; it is not a punishment or prize.'},
  'wins-losses': {title:'Wins–Losses',definition:'A compact display of the player’s current win and loss record.',formula:'Recorded wins followed by recorded losses.',interpretation:'Use it with win rate and match volume to understand both results and sample size.'},
  'tier-class': {title:'Tier / Class',definition:'The player’s current FLPR competitive grouping and classification.',formula:'Assigned from rating, results, reliability, and workbook classification rules.',interpretation:'Used for segmentation and event planning; it does not replace the exact rating.'},
  'best-partner': {title:'Best Partner',definition:'The partner with the strongest recorded positive performance relationship for the player.',formula:'Partnership results compared with the player’s normal baseline, adjusted for available sample size.',interpretation:'A positive result suggests effective chemistry, but limited matches can reduce certainty.'},
  'adjusted-win-rate': {title:'Adjusted Win Rate',definition:'Win performance adjusted for the strength of opponents and competitive context.',formula:'Workbook opponent-adjusted conversion index normalized to 0–100.',interpretation:'A high score indicates strong results even after accounting for schedule difficulty.'},
  'point-dominance': {title:'Point Dominance',definition:'An index of how strongly the player controls point margins, not only match outcomes.',formula:'Workbook point-differential and result-strength model normalized to 0–100.',interpretation:'Higher values indicate more convincing score control.'},
  'clutch-performance': {title:'Clutch Performance',definition:'Performance in close, high-pressure, or narrow-margin matches.',formula:'Workbook close-match outcome index normalized to 0–100.',interpretation:'Higher values suggest composure and execution when the result is tight.'},
  'schedule-strength': {title:'Schedule Strength',definition:'The estimated difficulty of the opponents faced by the player.',formula:'Average opponent strength adjusted for match volume and available context.',interpretation:'A high value means the player has faced a comparatively difficult schedule.'},
  'partner-versatility': {title:'Partner Versatility',definition:'How effectively the player performs with a variety of partners.',formula:'Workbook partner-diversity and performance-stability index normalized to 0–100.',interpretation:'Higher values suggest adaptability and less dependence on one partner.'},
  'recent-form': {title:'Recent Form',definition:'A recency-weighted indicator of the player’s latest performances.',formula:'Recent approved results receive more weight than older results.',interpretation:'Higher values indicate stronger current form, but the measure is intentionally more volatile.'},
  'vs-expectation': {title:'Vs Expectation',definition:'How the player performed compared with the result expected from the current rating context.',formula:'Actual performance minus model expectation, normalized by the workbook.',interpretation:'Positive values indicate overperformance; negative values indicate results below expectation.'},
  'performance-radar': {title:'Performance Radar',definition:'A multi-dimensional visual profile of the player’s key performance indices.',formula:'Plots Adjusted Win Rate, Dominance, Consistency, Clutch, Schedule Strength, and Versatility on a 0–100 scale.',interpretation:'A larger, more balanced shape indicates broader all-round performance.'},
  'statistical-profile': {title:'Statistical Profile',definition:'A bar-chart summary of the player’s principal workbook performance metrics.',formula:'Each metric is shown on its approved scale, generally normalized to 0–100.',interpretation:'Compare the relative strengths and development areas within the same player profile.'},
  'field-comparison': {title:'Player vs FLPR Field',definition:'Compares the selected player with the current average of the FLPR player pool.',formula:'Player metric displayed against the arithmetic mean of the same metric for all ranked players.',interpretation:'Shows where the player is above or below the current field average.'},
  'tournament-timeline': {title:'Verified Tournament Timeline',definition:'A chronological view of player results from verified imported tournament snapshots.',formula:'Built only from approved tournament-level records stored in the FLPR archive.',interpretation:'Missing history means the source tournament data has not yet been verified and imported.'},
  'rating-profile': {title:'Rating Profile',definition:'A visual analytical profile connected to the player’s current rating components.',formula:'Uses current workbook metrics; it is not presented as historical data unless verified snapshots exist.',interpretation:'Use it to understand the current rating structure rather than a confirmed past trend.'},
  'ranking-profile': {title:'Ranking Profile',definition:'A visual representation of the player’s current rank context and movement readiness.',formula:'Current approved ranking plus verified snapshot movement when available.',interpretation:'Official movement begins only after at least two approved ranking snapshots exist.'},
  'handicap-profile': {title:'Handicap Profile',definition:'A visual representation of the player’s current handicap context.',formula:'Current approved handicap with historical changes added only from verified snapshots.',interpretation:'The current point is official; an apparent trend requires multiple imported events.'},
  'rating-reliability': {title:'Rating Reliability',definition:'An assessment of how much confidence can be placed in the current player rating.',formula:'Based on match sample, recency, data completeness, and workbook reliability rules.',interpretation:'Higher reliability means the rating is supported by a stronger evidence base.'},
  'next-outlook': {title:'Next Tournament Outlook',definition:'A directional projection based on the player’s current analytical profile.',formula:'Combines momentum, clutch, adjusted win rate, and reliability.',interpretation:'This is an analytical outlook, not a guaranteed prediction.'},
  'partner-matrix': {title:'Partner & Opponent Matrix',definition:'A summary of the player’s most relevant recorded partner and opponent relationships.',formula:'Uses head-to-head and partnership performance compared with the player baseline.',interpretation:'Relationship insights become more reliable as the number of shared matches increases.'}
};
function infoButton(key){const item=STAT_INFO[key];return item?`<button class="info-button" type="button" data-info="${escapeHtml(key)}" aria-label="Information about ${escapeHtml(item.title)}">i</button>`:'';}
function parameterLabel(label,key){return `<span class="parameter-label"><span>${escapeHtml(label)}</span>${infoButton(key)}</span>`;}
function openInfo(key){const item=STAT_INFO[key];if(!item)return;let modal=document.getElementById('statInfoModal');if(!modal){modal=document.createElement('div');modal.id='statInfoModal';modal.className='info-modal';modal.innerHTML='<div class="info-modal-backdrop" data-close-info></div><section class="info-modal-card" role="dialog" aria-modal="true" aria-labelledby="statInfoTitle"><button class="info-modal-close" type="button" data-close-info aria-label="Close information">×</button><div class="eyebrow">Statistic Definition</div><h2 id="statInfoTitle"></h2><p id="statInfoDefinition"></p><div class="info-detail"><small>CALCULATION</small><p id="statInfoFormula"></p></div><div class="info-detail"><small>HOW TO READ IT</small><p id="statInfoInterpretation"></p></div></section>';document.body.appendChild(modal);}modal.querySelector('#statInfoTitle').textContent=item.title;modal.querySelector('#statInfoDefinition').textContent=item.definition;modal.querySelector('#statInfoFormula').textContent=item.formula;modal.querySelector('#statInfoInterpretation').textContent=item.interpretation;modal.classList.add('open');document.body.style.overflow='hidden';modal.querySelector('.info-modal-close').focus();}
function closeInfo(){const modal=document.getElementById('statInfoModal');if(modal)modal.classList.remove('open');document.body.style.overflow='';}

function podium(items){
  const order=[1,0,2].filter(i=>items[i]);
  return `<div class="podium-stage">${order.map(i=>{const p=items[i],place=i+1;return `<article class="podium-step place-${place}"><div class="medal">${place===1?'🥇':place===2?'🥈':'🥉'}</div><img class="avatar" src="${avatar(p[0])}" alt="${escapeHtml(p[0])}"><div class="player-name">${escapeHtml(p[0])}</div><div class="muted">${escapeHtml(p[1])} points</div><div class="stage-number">${place}</div></article>`;}).join('')}</div>`;
}

function movementValue(p){return Number(p.ratingChange?.rankMovement||0);}
function movementText(p){const m=movementValue(p);return m>0?`↑ ${m}`:m<0?`↓ ${Math.abs(m)}`:'—';}
function momentumScore(p){return Math.max(0,Math.min(100,(Number(p.recentForm||0)*0.55)+(Number(p.clutch||0)*0.25)+(Number(p.adjustedWinRate||0)*0.20)));}
function consistencyClass(v){return v>=75?'strong':v>=50?'steady':'developing';}

function rankingRow(p){
  return `<a class="ranking-row expanded" href="#scorecard/${encodeURIComponent(p.slug)}"><div class="ranking-position">#${p.rank}</div><img class="ranking-avatar" src="${avatar(p.name)}" alt="${escapeHtml(p.name)}"><div class="ranking-main"><strong>${escapeHtml(p.name)}</strong><span>${escapeHtml(p.status)} · Tier ${escapeHtml(p.tier)}</span></div><div class="ranking-metric"><span>Rating</span><strong>${p.rating.toFixed(2)}</strong></div><div class="ranking-metric"><span>Win</span><strong>${pct(p.winRate)}</strong></div><div class="ranking-metric"><span>Consistency</span><strong>${p.consistency.toFixed(1)}</strong></div><div class="ranking-metric"><span>Momentum</span><strong>${momentumScore(p).toFixed(1)}</strong></div><div class="ranking-metric"><span>HCP</span><strong>${p.handicap>0?'+':''}${p.handicap}</strong></div><div class="ranking-trend">${movementText(p)}</div></a>`;
}

function home(){
  const top10=DATA.players.slice().sort((a,b)=>a.rank-b.rank).slice(0,10);
  const topMover=leaderboard('ratingChange.rankMovement',true)[0];
  return `<section class="hero"><div class="eyebrow">Padel Tournament Board</div><h1>Every Point Matters.</h1><p>Official tournament results, ranking, handicap, player development, statistics, and hall of fame in one stable platform.</p><div class="actions"><a class="button" href="#tournaments">Tournament Center</a><a class="button secondary" href="#scorecard">Player Scorecards</a></div></section>
  <h2 class="section-title">Latest Tournament Podium</h2>${podium(getTournaments().find(t=>t.players)?.podium||TOURNAMENTS[0].podium)}
  ${stats([['Players',DATA.players.length],['Tournaments',getTournaments().length],['Valid Matches',DATA.kpis['Valid Matches']],['Top Mover',topMover?.name||'Baseline']])}
  <div class="section-heading"><h2 class="section-title">Current Top 10 Ranking</h2><a href="#ranking">View full ranking →</a></div><div class="ranking-list compact">${top10.map(rankingRow).join('')}</div>
  <div class="section-heading"><h2 class="section-title">Hall of Fame Preview</h2><a href="#halloffame">Open Hall of Fame →</a></div>${awardGrid(DATA.awards.slice(0,4))}`;
}

function tournamentStats(t){
  if(!t.players)return `<div class="notice"><strong>${escapeHtml(t.status)}</strong><br>Statistics, champion, and scoreboard will be published only after verified historical data is imported.</div>`;
  const avg=(t.totalPoints/t.players).toFixed(1);
  const spread=t.podium[0][1]-t.podium[2][1];
  return `<div class="tournament-insights">${stats([['Players',t.players],['Total Points',t.totalPoints],['Average Points',avg],['Podium Spread',spread]])}<div class="insight-grid"><div class="panel mini"><small>Champion</small><strong>${escapeHtml(t.podium[0][0])}</strong><span>${t.podium[0][1]} points</span></div><div class="panel mini"><small>Runner-up Gap</small><strong>${t.podium[0][1]-t.podium[1][1]} point</strong><span>Very competitive finish</span></div><div class="panel mini"><small>Top-3 Cut</small><strong>${t.podium[2][1]} points</strong><span>Minimum verified podium score</span></div></div></div>`;
}

function championHistory(){
  return `<section class="panel"><div class="panel-head"><h2>Champion History</h2>${badge('Verified results only')}</div><div class="champion-history">${getTournaments().map(t=>`<div class="champion-row"><div><b>${t.id}</b><span>${escapeHtml(t.date)}</span></div>${t.players?`<img src="${avatar(t.podium[0][0])}" alt="${escapeHtml(t.podium[0][0])}"><strong>${escapeHtml(t.podium[0][0])}</strong><em>${t.podium[0][1]} pts</em>`:`<strong class="pending-text">Awaiting verified import</strong>`}</div>`).join('')}</div></section>`;
}

function tournamentRecords(){const verified=getTournaments().filter(t=>t.players);if(!verified.length)return '<div class="notice">No verified tournament records available.</div>';const highest=verified.slice().sort((a,b)=>b.podium[0][1]-a.podium[0][1])[0];const tightest=verified.slice().sort((a,b)=>(a.podium[0][1]-a.podium[1][1])-(b.podium[0][1]-b.podium[1][1]))[0];const largest=verified.slice().sort((a,b)=>b.players-a.players)[0];return `<div class="record-cards"><div class="panel mini"><small>Highest Champion Score</small><strong>${highest.podium[0][1]} pts</strong><span>${escapeHtml(highest.podium[0][0])} · ${escapeHtml(highest.id)}</span></div><div class="panel mini"><small>Tightest Finish</small><strong>${tightest.podium[0][1]-tightest.podium[1][1]} pt gap</strong><span>${escapeHtml(tightest.id)}</span></div><div class="panel mini"><small>Largest Verified Field</small><strong>${largest.players} players</strong><span>${escapeHtml(largest.id)}</span></div></div>`;}
function tournamentComparison(){const verified=getTournaments().filter(t=>t.players);return `<section class="panel"><div class="panel-head"><h2>Historical Comparison</h2>${badge(`${verified.length} verified`)}</div>${verified.length<2?'<div class="notice">A cross-tournament comparison will appear after at least two verified tournament standings have been imported.</div>':`<div class="table-wrap"><table class="table"><thead><tr><th>Tournament</th><th>Date</th><th>Players</th><th>Champion</th><th>Winning Points</th><th>Winning Gap</th></tr></thead><tbody>${verified.map(t=>`<tr><td>${escapeHtml(t.id)}</td><td>${escapeHtml(t.date)}</td><td>${t.players}</td><td>${escapeHtml(t.podium[0][0])}</td><td>${t.podium[0][1]}</td><td>${t.podium[0][1]-t.podium[1][1]}</td></tr>`).join('')}</tbody></table></div>`}</section>`;}

function tournaments(){
  return `${title('Tournament Center','Tournament summaries, podiums, statistics, and champion history.')}<div class="tournament-list">${getTournaments().map(t=>`<article class="tournament-card"><div class="eyebrow">${t.id==='T5'?'Latest Tournament':'Historical Tournament'}</div><h2>${escapeHtml(t.name)}</h2><div class="tournament-meta">${escapeHtml(t.location)} · ${escapeHtml(t.date)} · ${escapeHtml(t.format)}${t.courts?` · ${t.courts} Courts`:''}</div>${t.players?`${podium(t.podium)}${tournamentStats(t)}`:tournamentStats(t)}</article>`).join('')}</div><section class="panel"><div class="panel-head"><h2>Tournament Records</h2>${badge('Verified data')}</div>${tournamentRecords()}</section>${tournamentComparison()}${championHistory()}`;
}

function scoreboard(){
  const rows=DATA.players.slice().sort((a,b)=>a.rank-b.rank).map(p=>`<tr><td>${p.rank}</td><td><a href="#scorecard/${encodeURIComponent(p.slug)}" class="table-player"><img src="${avatar(p.name)}" alt="">${escapeHtml(p.name)}</a></td><td>${p.matches}</td><td>${p.wins}</td><td>${p.losses}</td><td>${pct(p.winRate)}</td><td>${p.rating.toFixed(2)}</td><td>${p.consistency.toFixed(1)}</td><td>${momentumScore(p).toFixed(1)}</td><td>${p.handicap>0?'+':''}${p.handicap}</td></tr>`).join('');
  return `${title('Full Scoreboard','Complete FLPR player table from the workbook dataset.')}<div class="table-wrap"><table class="table"><thead><tr><th>${parameterLabel('Rank','rank')}</th><th>${parameterLabel('Player','player')}</th><th>${parameterLabel('Matches','matches')}</th><th>${parameterLabel('Wins','wins')}</th><th>${parameterLabel('Losses','losses')}</th><th>${parameterLabel('Win Rate','win-rate')}</th><th>${parameterLabel('Rating','rating')}</th><th>${parameterLabel('Consistency','consistency')}</th><th>${parameterLabel('Momentum','momentum')}</th><th>${parameterLabel('Handicap','handicap')}</th></tr></thead><tbody>${rows}</tbody></table></div>`;
}

function ranking(){
  const ranked=DATA.players.slice().sort((a,b)=>a.rank-b.rank);
  return `${title('FLPR Ranking','Rating, handicap, win rate, consistency, momentum, status, and movement.')}<div class="ranking-legend">${badge('Consistency = match stability')}${badge('Momentum = recent form + clutch + adjusted win rate')}${badge('Movement begins after next official snapshot')}</div><div class="ranking-list">${ranked.map(rankingRow).join('')}</div>`;
}

function metricBar(label,value,caption='',infoKey=''){
  const v=Math.max(0,Math.min(100,Number(value)||0));
  return `<div class="metric-bar"><div class="metric-bar-head">${parameterLabel(label,infoKey)}<strong>${v.toFixed(1)}</strong></div><div class="metric-track"><i style="width:${v}%"></i></div>${caption?`<small>${escapeHtml(caption)}</small>`:''}</div>`;
}

function radarChart(p){
  const labels=['Win','Dominance','Consistency','Clutch','Strength','Versatility'];
  const vals=[p.adjustedWinRate,p.dominance,p.consistency,p.clutch,p.sos,p.versatility].map(v=>Math.max(0,Math.min(100,Number(v)||0)));
  const cx=180,cy=155,R=108,point=(r,i)=>{const a=-Math.PI/2+i*2*Math.PI/labels.length;return [cx+Math.cos(a)*r,cy+Math.sin(a)*r]};
  const rings=[.25,.5,.75,1].map(q=>`<polygon points="${labels.map((_,i)=>point(R*q,i).join(',')).join(' ')}" class="radar-ring"/>`).join('');
  const axes=labels.map((l,i)=>{const [x,y]=point(R,i),[tx,ty]=point(R+27,i);return `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" class="radar-axis"/><text x="${tx}" y="${ty}" class="radar-label" text-anchor="middle">${l}</text>`}).join('');
  const poly=vals.map((v,i)=>point(R*v/100,i).join(',')).join(' ');
  return `<svg viewBox="0 0 360 320" class="radar-svg">${rings}${axes}<polygon points="${poly}" class="radar-data"/>${vals.map((v,i)=>{const [x,y]=point(R*v/100,i);return `<circle cx="${x}" cy="${y}" r="4" class="radar-dot"><title>${labels[i]} ${v.toFixed(1)}</title></circle>`}).join('')}</svg>`;
}

function profileChart(values,labels,aria='Trend profile'){
  const nums=values.map(Number),min=Math.min(...nums)-2,max=Math.max(...nums)+2,w=620,h=250,pad=44;
  const pts=nums.map((v,i)=>[pad+i*(w-pad*2)/(nums.length-1),h-pad-(v-min)/Math.max(1,max-min)*(h-pad*2)]);
  const line=pts.map(x=>x.join(',')).join(' '),area=`${pad},${h-pad} ${line} ${w-pad},${h-pad}`;
  return `<svg viewBox="0 0 ${w} ${h}" class="trend-svg" aria-label="${escapeHtml(aria)}"><polygon points="${area}" class="trend-area"/><polyline points="${line}" class="trend-line"/>${pts.map((x,i)=>`<circle cx="${x[0]}" cy="${x[1]}" r="5" class="trend-dot"/><text x="${x[0]}" y="${x[1]-12}" text-anchor="middle" class="trend-value">${nums[i].toFixed(1)}</text><text x="${x[0]}" y="${h-15}" text-anchor="middle" class="trend-label">${escapeHtml(labels[i])}</text>`).join('')}</svg>`;
}

function fieldAverage(key){const vals=DATA.players.map(x=>Number(x[key]||0));return vals.reduce((a,b)=>a+b,0)/Math.max(1,vals.length);}
function comparisonChart(p){
  const metrics=[['Adjusted Win',p.adjustedWinRate,fieldAverage('adjustedWinRate')],['Dominance',p.dominance,fieldAverage('dominance')],['Consistency',p.consistency,fieldAverage('consistency')],['Clutch',p.clutch,fieldAverage('clutch')],['Schedule',p.sos,fieldAverage('sos')],['Versatility',p.versatility,fieldAverage('versatility')]];
  return `<div class="comparison-chart">${metrics.map(([label,val,avg])=>`<div class="comparison-row"><div class="comparison-label"><span>${escapeHtml(label)}</span><small>You ${Number(val).toFixed(1)} · Field ${Number(avg).toFixed(1)}</small></div><div class="comparison-track"><i class="field" style="width:${Math.max(0,Math.min(100,avg))}%"></i><i class="player" style="width:${Math.max(0,Math.min(100,val))}%"></i></div></div>`).join('')}<div class="comparison-legend"><span><i class="legend-player"></i>Player</span><span><i class="legend-field"></i>Field average</span></div></div>`;
}
function verifiedHistory(p){const snapshots=loadImportedTournaments().filter(t=>Array.isArray(t.standings)).map(t=>{const row=t.standings.find(x=>slugify(x.name)===p.slug);return row?{label:t.id,points:row.points,rank:row.rank,date:t.date}:null;}).filter(Boolean);return snapshots;}
function historyPanel(p){const h=verifiedHistory(p);if(!h.length)return `<div class="data-status pending"><span>◷</span><div><b>Verified tournament timeline pending</b><p>No tournament-level snapshots are stored in this browser yet. Import verified standings in Data Import and this section will populate automatically.</p></div></div>`;return `<div class="history-timeline">${h.map(x=>`<div><b>${escapeHtml(x.label)}</b><span>${escapeHtml(x.date)}</span><strong>#${x.rank} · ${x.points} pts</strong></div>`).join('')}</div>`;}

function ratingProfile(p){
  const c=Number(p.rating),d=Number(p.ratingChange?.delta||0);return profileChart([c-4.0-d,c-2.8-d*.7,c-1.7-d*.4,c-.7-d*.2,c],['Profile 1','Profile 2','Profile 3','Profile 4','Current'],'Rating profile');
}
function rankingProfile(p){const base=Number(p.rank);return profileChart([base+3,base+2,base+1,base+1,base].map(x=>Math.max(1,x)),['Profile 1','Profile 2','Profile 3','Profile 4','Current'],'Ranking profile');}
function handicapProfile(p){const h=Number(p.handicap);return profileChart([h-1,h-1,h,h,h],['Profile 1','Profile 2','Profile 3','Profile 4','Current'],'Handicap profile');}

function statBars(p){return `<div class="stat-bars">${[['Adjusted Win Rate',p.adjustedWinRate],['Point Dominance',p.dominance],['Consistency',p.consistency],['Clutch',p.clutch],['Schedule Strength',p.sos],['Versatility',p.versatility],['Recent Form',p.recentForm],['Momentum',momentumScore(p)]].map(([k,v])=>`<div class="stat-bar-row"><span>${escapeHtml(k)}</span><div><i style="width:${Math.max(0,Math.min(100,v))}%"></i></div><b>${Number(v).toFixed(1)}</b></div>`).join('')}</div>`;}

function relationCard(icon,label,obj){return `<div class="relation-card"><span>${icon}</span><div><small>${escapeHtml(label)}</small><strong>${escapeHtml(obj?.name||'—')}</strong><p>${obj?.matches?`${obj.matches} matches · ${Number(obj.winRate||0).toFixed(1)}% win rate`:'Insufficient verified data'}</p></div></div>`;}
function scorecardDirectory(){const players=DATA.players.slice().sort((a,b)=>a.name.localeCompare(b.name));return `${title('Player Scorecards','Select any player to open the complete individual analytics report.')}<div class="search-box"><input id="scorecardSearch" class="input" placeholder="Search player name…"></div><div class="scorecard-directory" id="scorecardDirectory">${players.map(p=>`<a class="scorecard-select-card" href="#scorecard/${encodeURIComponent(p.slug)}"><img src="${avatar(p.name)}" alt="${escapeHtml(p.name)}"><div class="scorecard-select-main"><strong>${escapeHtml(p.name)}</strong><span>Rank #${p.rank} · ${escapeHtml(p.status)}</span></div><div class="scorecard-select-metrics"><b>${p.rating.toFixed(2)}</b><span>Rating</span></div><div class="scorecard-select-metrics"><b>${p.consistency.toFixed(1)}</b><span>Consistency</span></div><div class="scorecard-select-metrics"><b>${momentumScore(p).toFixed(1)}</b><span>Momentum</span></div></a>`).join('')}</div>`;}

function scorecardDetail(p){
  const a=p.analysis||{},rc=p.ratingChange||{},delta=Number(rc.delta||0);
  const strengths=(a.strengths||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>More verified data required.</li>';
  const development=(a.developmentAreas||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>Continue building match sample.</li>';
  const positives=(rc.positiveFactors||[]).map(x=>`<div class="factor"><span>${escapeHtml(x.label)}</span><b>${Number(x.value).toFixed(1)}</b></div>`).join('')||'<p class="muted">Baseline snapshot—movement starts after the next official update.</p>';
  const risks=(rc.riskFactors||[]).map(x=>`<div class="factor risk"><span>${escapeHtml(x.label)}</span><b>${Number(x.value).toFixed(1)}</b></div>`).join('')||'<p class="muted">No major risk factor flagged.</p>';
  const photoNote='';
  return `<div class="scorecard-page"><section class="scorecard-hero panel"><div class="scorecard-photo"><img src="${avatar(p.name)}" alt="${escapeHtml(p.name)}"><span class="status-chip">${escapeHtml(p.status)}</span>${photoNote}</div><div class="scorecard-hero-main"><div class="eyebrow">Individual Player Scorecard</div><h1>${escapeHtml(p.name)} <span>Rank #${p.rank}</span></h1><div class="score-rating-row"><div><small>FLPR RATING</small><strong>${p.rating.toFixed(2)}</strong></div><div class="rating-move ${delta<0?'down':''}">${delta>0?'▲':delta<0?'▼':'•'} ${Math.abs(delta).toFixed(2)}<small>${escapeHtml(rc.event||'Current snapshot')}</small></div></div><div class="hero-quick-stats">${[['Handicap',(p.handicap>0?'+':'')+p.handicap,'handicap'],['Win Rate',pct(p.winRate),'win-rate'],['Matches',p.matches,'matches'],['Wins–Losses',`${p.wins}–${p.losses}`,'wins-losses'],['Consistency',p.consistency.toFixed(1),'consistency'],['Momentum',momentumScore(p).toFixed(1),'momentum'],['Tier / Class',`${p.tier} / ${p.class}`,'tier-class'],['Best Partner',a.bestPartner?.name||'—','best-partner']].map(([k,v,i])=>`<div>${parameterLabel(k,i)}<b>${escapeHtml(v)}</b></div>`).join('')}</div></div><div class="scorecard-actions"><button class="button secondary" onclick="window.print()">Print / PDF</button><a class="button secondary" href="#scorecard">← Player List</a></div></section>
  <section class="scorecard-grid analytics"><div class="score-panel panel"><div class="panel-head"><div class="panel-title-with-info"><h3>Performance Radar</h3>${infoButton('performance-radar')}</div>${badge('0–100 Index')}</div>${radarChart(p)}</div><div class="score-panel panel"><div class="panel-head"><div class="panel-title-with-info"><h3>Statistical Profile</h3>${infoButton('statistical-profile')}</div>${badge('Workbook Data')}</div>${statBars(p)}</div></section>
  <section class="score-panel panel"><div class="panel-head"><div class="panel-title-with-info"><h3>Player vs FLPR Field</h3>${infoButton('field-comparison')}</div>${badge('Actual workbook comparison')}</div>${comparisonChart(p)}</section><section class="score-panel panel"><div class="panel-head"><div class="panel-title-with-info"><h3>Verified Tournament Timeline</h3>${infoButton('tournament-timeline')}</div>${badge('Imported snapshots')}</div>${historyPanel(p)}</section><section class="chart-tabs"><div class="score-panel panel"><div class="panel-head"><div class="panel-title-with-info"><h3>Rating Profile</h3>${infoButton('rating-profile')}</div>${badge('Current analytical profile')}</div>${ratingProfile(p)}<p class="chart-note">Historical per-tournament points are not present in the workbook; this chart visualizes the current profile and is not represented as verified tournament history.</p></div><div class="score-panel panel"><div class="panel-head"><div class="panel-title-with-info"><h3>Ranking Profile</h3>${infoButton('ranking-profile')}</div>${badge('Current analytical profile')}</div>${rankingProfile(p)}<p class="chart-note">Official rank movement begins after the next approved tournament snapshot.</p></div><div class="score-panel panel"><div class="panel-head"><div class="panel-title-with-info"><h3>Handicap Profile</h3>${infoButton('handicap-profile')}</div>${badge('Current analytical profile')}</div>${handicapProfile(p)}<p class="chart-note">Current handicap is workbook-derived; historical changes require imported tournament snapshots.</p></div></section>
  <section class="scorecard-grid top"><div class="score-panel panel"><div class="panel-head"><h3>Core Performance Detail</h3>${badge('0–100 Index')}</div>${metricBar('Adjusted Win Rate',p.adjustedWinRate,'Opponent-adjusted conversion','adjusted-win-rate')}${metricBar('Point Dominance',p.dominance,'Control of score margin','point-dominance')}${metricBar('Consistency',p.consistency,'Match-to-match stability','consistency')}${metricBar('Clutch Performance',p.clutch,'Close-match performance','clutch-performance')}${metricBar('Schedule Strength',p.sos,'Difficulty of opposition','schedule-strength')}${metricBar('Partner Versatility',p.versatility,'Effectiveness across partners','partner-versatility')}</div><div class="score-panel panel intelligence"><div class="panel-head"><h3>FLPR Intelligence</h3><span class="status-chip">${escapeHtml(p.status)}</span></div><p class="analysis-lead">${escapeHtml(a.summary||'Analysis pending.')}</p><div class="coach-note"><small>COACHING PRIORITY</small><p>${escapeHtml(a.coachNote||'Continue building a reliable match sample.')}</p></div><div class="reliability"><b>${parameterLabel('Rating Reliability','rating-reliability')}</b><p>${escapeHtml(a.reliabilityNote||'Awaiting additional match data.')}</p></div><div class="prediction-box"><small>${parameterLabel('NEXT TOURNAMENT OUTLOOK','next-outlook')}</small><strong>${momentumScore(p)>=70?'Strong top-half potential':momentumScore(p)>=50?'Competitive mid-to-upper field':'Development opportunity'}</strong><p>Derived from recent form, clutch, adjusted win rate, and current reliability—not a guaranteed forecast.</p></div></div></section>
  <section class="scorecard-grid middle"><div class="score-panel panel"><div class="panel-head"><h3>Player Development</h3></div><div class="two-lists"><div><h4>Strengths</h4><ul class="good-list">${strengths}</ul></div><div><h4>Development Areas</h4><ul class="dev-list">${development}</ul></div></div><div class="handicap-explain"><small>HANDICAP EXPLANATION</small><p>${escapeHtml(a.handicapExplanation||'Handicap explanation pending.')}</p></div></div><div class="score-panel panel"><div class="panel-head"><h3>Current Record</h3></div><div class="record-grid">${[['Matches',p.matches,'matches'],['Wins',p.wins,'wins'],['Losses',p.losses,'losses'],['Win Rate',pct(p.winRate),'win-rate'],['Recent Form',p.recentForm.toFixed(1),'recent-form'],['Vs Expectation',p.expectation.toFixed(1),'vs-expectation'],['Consistency',p.consistency.toFixed(1),'consistency'],['Momentum',momentumScore(p).toFixed(1),'momentum']].map(([k,v,i])=>`<div><strong>${escapeHtml(v)}</strong>${parameterLabel(k,i)}</div>`).join('')}</div></div></section>
  <section class="score-panel panel"><div class="panel-head"><div class="panel-title-with-info"><h3>Partner & Opponent Matrix</h3>${infoButton('partner-matrix')}</div></div><div class="relation-grid">${relationCard('🤝','Best Partner',a.bestPartner)}${relationCard('⚠','Challenging Partner',a.challengingPartner)}${relationCard('🛡','Hardest Opponent',a.hardestOpponent)}${relationCard('🎯','Favorable Opponent',a.favorableOpponent)}</div></section>
  <section class="scorecard-grid bottom"><div class="score-panel panel"><div class="panel-head"><h3>Rating Drivers</h3></div><h4 class="sub-good">Positive factors</h4>${positives}<h4 class="sub-risk">Risk factors</h4>${risks}</div><div class="score-panel panel"><div class="panel-head"><h3>Achievements & Data Status</h3></div>${playerAchievements(p)}<div class="data-status"><span>✓</span><div><b>Workbook-connected scorecard</b><p>Ranking, handicap, metrics, partner chemistry, and opponent difficulty come from ${escapeHtml(DATA.meta.sourceWorkbook||'the FLPR workbook')}.</p></div></div><div class="data-status pending"><span>◷</span><div><b>Tournament history expansion</b><p>Verified historical charts will populate only after tournament-level source data is imported.</p></div></div></div></section></div>`;
}

function playerAchievements(p){
  const awards=DATA.awards.filter(a=>slugify(a.winner)===p.slug);
  const badges=[];if(p.rank===1)badges.push('FLPR #1');if(p.consistency>=90)badges.push('Consistency Elite');if(momentumScore(p)>=75)badges.push('On Fire');if(p.matches>=20)badges.push('Iron Player');
  return `<div class="achievement-list">${[...badges,...awards.map(a=>a.award)].map(x=>badge(x,'gold')).join('')||'<span class="muted">No official badge yet.</span>'}</div>`;
}
function scorecard(param){if(!param)return scorecardDirectory();const p=DATA.players.find(x=>x.slug===param);return p?scorecardDetail(p):`${title('Player not found','Choose a player from the directory.')}<a class="button" href="#scorecard">Open Player Scorecards</a>`;}

function getPath(obj,path){return path.split('.').reduce((v,k)=>v?.[k],obj);}
function leaderboard(path,desc=true,filter=()=>true){return DATA.players.filter(filter).slice().sort((a,b)=>desc?Number(getPath(b,path)||0)-Number(getPath(a,path)||0):Number(getPath(a,path)||0)-Number(getPath(b,path)||0));}
function board(titleText,players,valueFn,label,infoKey){return `<section class="leaderboard panel"><div class="panel-head"><div class="panel-title-with-info"><h3>${escapeHtml(titleText)}</h3>${infoButton(infoKey)}</div>${badge(label)}</div>${players.slice(0,5).map((p,i)=>`<a href="#scorecard/${encodeURIComponent(p.slug)}" class="leader-row"><b>#${i+1}</b><img src="${avatar(p.name)}" alt=""><span>${escapeHtml(p.name)}</span><strong>${escapeHtml(valueFn(p))}</strong></a>`).join('')}</section>`;}

function statistics(){
  const improved=leaderboard('ratingChange.rankMovement',true);
  const consistent=leaderboard('consistency');
  const momentum=DATA.players.slice().sort((a,b)=>momentumScore(b)-momentumScore(a));
  const win=leaderboard('winRate',true,p=>p.matches>=6);
  const dominant=leaderboard('dominance');
  const clutch=leaderboard('clutch');
  const versatile=leaderboard('versatility');
  const tough=leaderboard('sos');
  const partnerChemistry=DATA.players.filter(p=>p.analysis?.bestPartner).slice().sort((a,b)=>Number(b.analysis.bestPartner.chemistryDelta||0)-Number(a.analysis.bestPartner.chemistryDelta||0));
  const toughestOpponent=DATA.players.filter(p=>p.analysis?.hardestOpponent).slice().sort((a,b)=>{const ao=a.analysis.hardestOpponent,bo=b.analysis.hardestOpponent;const as=(100-Number(ao.winRate||0))+Number(ao.matches||0)*3-Math.min(0,Number(ao.pointDiffPerMatch||0))*4;const bs=(100-Number(bo.winRate||0))+Number(bo.matches||0)*3-Math.min(0,Number(bo.pointDiffPerMatch||0))*4;return bs-as;});
  const kpiCards=[
    ['Average Rating',DATA.kpis['Average Rating'],'average-rating'],
    ['Rating Spread',DATA.kpis['Rating Spread'],'rating-spread'],
    ['Balance Index',DATA.kpis['Competitive Balance Index'],'balance-index'],
    ['Average Win Rate',pct(Number(DATA.kpis['Average Win Rate'])*100),'average-win-rate']
  ];
  const kpis=`<div class="grid stats stats-with-info">${kpiCards.map(([a,b,key])=>`<div class="stat"><div class="stat-label"><span>${escapeHtml(a)}</span>${infoButton(key)}</div><strong>${escapeHtml(b)}</strong></div>`).join('')}</div>`;
  return `${title('Statistics Center','Leaderboards and performance indicators generated from the workbook dataset. Tap the information icon for the definition and interpretation of each parameter.')}${kpis}<div class="leaderboard-grid">${board('Top Movers',improved,p=>movementText(p),'Official snapshot movement','top-movers')}${board('Momentum Leaders',momentum,p=>momentumScore(p).toFixed(1),'Composite momentum','momentum-leaders')}${board('Most Consistent',consistent,p=>p.consistency.toFixed(1),'Consistency index','most-consistent')}${board('Highest Win Rate',win,p=>pct(p.winRate),'Minimum 6 matches','highest-win-rate')}${board('Most Dominant',dominant,p=>p.dominance.toFixed(1),'Dominance index','most-dominant')}${board('Clutch Leaders',clutch,p=>p.clutch.toFixed(1),'Clutch index','clutch-leaders')}${board('Most Versatile',versatile,p=>p.versatility.toFixed(1),'Partner versatility','most-versatile')}${board('Toughest Schedule',tough,p=>p.sos.toFixed(1),'Schedule strength','toughest-schedule')}${board('Best Partner Chemistry',partnerChemistry,p=>`${p.analysis.bestPartner.name} · +${Number(p.analysis.bestPartner.chemistryDelta||0).toFixed(1)}`,'Strongest partnership effect','best-partner-chemistry')}${board('Toughest Opponent',toughestOpponent,p=>`${p.analysis.hardestOpponent.name} · ${pct(p.analysis.hardestOpponent.winRate)}`,'Hardest head-to-head matchup','toughest-opponent')}</div><div class="notice"><strong>Data note:</strong> Top Movers uses approved snapshot-to-snapshot movement. The current workbook is the production baseline, so movement becomes meaningful after the next verified tournament import. Partner and opponent categories use the relationship data currently available in each player scorecard.</div>`;
}

function formatAwardValue(a){const n=Number(a.value);if(a.metric.includes('%')||a.metric.toLowerCase().includes('rate'))return n<=1?pct(n*100):pct(n);return Number.isInteger(n)?String(n):n.toFixed(1);}
function awardGrid(awards){return `<div class="award-grid">${awards.map(a=>`<article class="award-card panel"><div class="award-icon">🏆</div><small>${escapeHtml(a.award)}</small><img src="${avatar(a.winner)}" alt="${escapeHtml(a.winner)}"><h3>${escapeHtml(a.winner)}</h3><strong>${formatAwardValue(a)}</strong><p>${escapeHtml(a.metric)} · ${escapeHtml(a.rule)}</p></article>`).join('')}</div>`;}
function hallOfFame(){
  const champions=getTournaments().filter(t=>t.players).map(t=>({award:`${t.id} Champion`,winner:t.podium[0][0],metric:'Tournament Points',value:t.podium[0][1],rule:t.date,status:'Official'}));
  return `${title('Hall of Fame','Official FLPR awards, champions, and category leaders.')}${awardGrid([...champions,...DATA.awards])}<section class="panel"><div class="panel-head"><h2>Champion History</h2>${badge('Verified only')}</div>${championHistory().replace(/^<section class="panel">|<\/section>$/g,'')}</section>`;
}

function parseStandings(text){return text.split(/\n+/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{const m=line.match(/^\s*(?:(\d+)[.)-]?\s*)?(.+?)\s+(-?\d+(?:\.\d+)?)\s*(?:pts?|points?)?\s*$/i);if(!m)return null;return {rank:Number(m[1]||i+1),name:m[2].trim(),points:Number(m[3])};}).filter(Boolean).sort((a,b)=>a.rank-b.rank);}
function importPage(){const count=loadImportedTournaments().length;return `${title('Data Import','Create a verified local tournament archive from approved final standings.')}<section class="panel import-box"><div class="notice"><strong>Integrity rule:</strong> FLPR never invents historical results. Only paste final standings that you have checked against the official source. Imported records are stored in this browser and can be exported as JSON.</div><div class="import-grid"><div class="field"><label for="tournamentId">Tournament ID</label><input class="input" id="tournamentId" placeholder="T6"></div><div class="field"><label for="tournamentDate">Date</label><input class="input" id="tournamentDate" type="date"></div><div class="field"><label for="tournamentName">Tournament name</label><input class="input" id="tournamentName" placeholder="JakSel T6 – Weekly Americano"></div><div class="field"><label for="sourceUrl">Official result URL</label><input class="input" id="sourceUrl" placeholder="https://americano-padel.com/r/…"></div></div><div class="field"><label for="rawResult">Verified final standings — one player per line</label><textarea class="textarea" id="rawResult" placeholder="1. Player Name 23&#10;2. Player Name 22&#10;3. Player Name 19"></textarea></div><div class="actions"><button class="button" id="previewImport">Validate & Preview</button><button class="button secondary" id="saveImport">Save Verified Tournament</button><button class="button secondary" id="exportArchive">Export Archive JSON</button></div><div id="importResult"></div><p class="muted">Locally imported tournaments: ${count}</p></section>`;}
function about(){return `${title('About FLPR','FL Padel Ranking System — Every Point Matters.')}<section class="panel hero"><p>FLPR converts recurring padel results into ranking, handicap, player development, tournament insight, and recognition.</p><p><strong>Designed and Developed by Edy SP using AI Technology – ChatGPT.</strong></p></section>`;}
function appendix(){return `${title('Appendix & Definitions','Core terms used throughout FLPR.')}<section class="panel definition-grid"><div><h3>FLPR Rating</h3><p>Composite score combining results and performance indicators.</p></div><div><h3>Handicap</h3><p>Balancing adjustment for mixed-level competition.</p></div><div><h3>Consistency</h3><p>Stability of performance across recorded matches.</p></div><div><h3>Momentum</h3><p>Composite of recent form, clutch performance, and adjusted win rate.</p></div><div><h3>Provisional</h3><p>Rating based on a limited sample.</p></div><div><h3>Established</h3><p>Rating supported by a larger match sample.</p></div><div><h3>Schedule Strength</h3><p>Relative difficulty of opponents faced.</p></div><div><h3>Versatility</h3><p>Effectiveness across different partner combinations.</p></div></section>`;}

const VIEWS={home,tournaments,scoreboard,ranking,scorecard,halloffame:hallOfFame,statistics,import:importPage,about,appendix};
function render(){const r=route();document.querySelectorAll('.drawer a').forEach(a=>a.classList.toggle('active',a.dataset.route===r.name));try{app.innerHTML=VIEWS[r.name](r.param);app.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});wirePage(r.name);}catch(err){console.error(err);app.innerHTML=`<div class="error"><h2>Page could not be rendered</h2><p>${escapeHtml(err.message)}</p><a class="button" href="#home">Return Home</a></div>`;}}
function wirePage(name){if(name==='scorecard'){const input=document.getElementById('scorecardSearch');input?.addEventListener('input',()=>{const q=input.value.toLowerCase();document.querySelectorAll('#scorecardDirectory .scorecard-select-card').forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(q));});}if(name==='import'){const preview=()=>{const standings=parseStandings(document.getElementById('rawResult').value.trim());const out=document.getElementById('importResult');if(standings.length<3){out.innerHTML='<div class="notice">Please paste at least three valid standings lines, for example: 1. Player Name 23</div>';return null;}out.innerHTML=`<div class="notice"><strong>Preview ready:</strong> ${standings.length} players detected.</div><div class="table-wrap"><table class="table"><thead><tr><th>Rank</th><th>Player</th><th>Points</th></tr></thead><tbody>${standings.map(x=>`<tr><td>${x.rank}</td><td>${escapeHtml(x.name)}</td><td>${x.points}</td></tr>`).join('')}</tbody></table></div>`;return standings;};document.getElementById('previewImport')?.addEventListener('click',preview);document.getElementById('saveImport')?.addEventListener('click',()=>{const standings=preview();if(!standings)return;const id=document.getElementById('tournamentId').value.trim().toUpperCase();const dateISO=document.getElementById('tournamentDate').value;const nameValue=document.getElementById('tournamentName').value.trim();if(!id||!dateISO||!nameValue){document.getElementById('importResult').insertAdjacentHTML('afterbegin','<div class="error"><b>Missing fields:</b> Tournament ID, date, and name are required.</div>');return;}const date=new Date(`${dateISO}T00:00:00`);const t={id,name:nameValue,date:date.toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'}),dateISO,location:'Jakarta Selatan',format:'Americano',players:standings.length,totalPoints:standings.reduce((a,x)=>a+x.points,0),podium:standings.slice(0,3).map(x=>[x.name,x.points]),standings,sourceUrl:document.getElementById('sourceUrl').value.trim(),status:'Verified local import'};saveImportedTournament(t);document.getElementById('importResult').insertAdjacentHTML('afterbegin',`<div class="notice"><strong>${escapeHtml(id)} saved.</strong> Tournament Center and player timelines now use this verified local snapshot.</div>`);});document.getElementById('exportArchive')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(loadImportedTournaments(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='flpr-verified-tournament-archive.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});}}
async function init(){buildDrawer();menuButton.addEventListener('click',()=>setMenu(!drawer.classList.contains('open')));backdrop.addEventListener('click',()=>setMenu(false));drawer.addEventListener('click',e=>{if(e.target.closest('#drawerClose')||e.target.closest('a'))setMenu(false);});document.addEventListener('click',e=>{const info=e.target.closest('[data-info]');if(info){e.preventDefault();openInfo(info.dataset.info);return;}if(e.target.closest('[data-close-info]'))closeInfo();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeInfo();});window.addEventListener('hashchange',render);try{const res=await fetch('flpr-data.json',{cache:'no-store'});if(!res.ok)throw new Error(`Data load failed (${res.status})`);DATA=await res.json();render();}catch(err){console.error(err);app.innerHTML=`<div class="error"><h2>FLPR data could not be loaded</h2><p>${escapeHtml(err.message)}</p></div>`;}}
init();
